stages:
  - testing
  - release
  - build production

cache:
  key: '$CI_PIPELINE_ID'
  paths:
    - /root/.cache
    - /root/.npm
    - node_modules

.before_script_template: &before-script
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_DOMAIN

testing:
  stage: testing
  image: node:14
  script:
    - npm install
    - npm run lint
    - npm run test

production:
  stage: build production
  image: docker:stable
  only:
    - master
  <<: *before-script
  script:
    - PACKAGE_VERSION=$(grep version package.json | cut -c 15- | rev | cut -c 3-
      | rev)
    - docker build . --build-arg PACKAGE_VERSION=$PACKAGE_VERSION --build-arg
      NODE_ENV=production --target production-stage -t
      $REGISTRY_DOMAIN/chrisleekr/binance-trading-bot:latest
    - docker push $REGISTRY_DOMAIN/chrisleekr/binance-trading-bot:latest
